try {
    f1(x);
    f2(x);
    f3(x);
    f4(x);
    f5(x);
    f6(x);
    f7(x);
    f8(x);
} catch (std::execption& e) {
    cout << e.what() << '\n';
}
